# Generated by Django 4.2.2 on 2024-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='categoryId',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='category_name',
            new_name='categoryName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='priceSales',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='pubDate',
        ),
        migrations.RemoveField(
            model_name='book',
            name='fixed_price',
        ),
        migrations.AddField(
            model_name='book',
            name='priceStandard',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
