# Generated by Django 4.2.2 on 2024-03-26 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Isbn',
            field=models.CharField(max_length=10),
        ),
    ]
