# Generated by Django 4.2.2 on 2024-04-14 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articst',
            new_name='Artist',
        ),
    ]
