# Generated by Django 4.2.11 on 2024-04-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_category_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
